apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: system-apps
  namespace: openshift-gitops
spec:
  generators:
  - git:
      repoURL: https://github.com/christianh814/ocp-sm-ar
      revision: main
      directories:
      - path: system/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      ignoreDifferences:
      - group: networking.istio.io
        kind: VirtualService
        jsonPointers:
        - /spec/http/0
      - kind: ConfigMap
        jsonPointers:
        - /data/service-ca.crt
      project: system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - ApplyOutOfSyncOnly=true
        retry:
          limit: 15
          backoff:
            duration: 15s
            factor: 2
            maxDuration: 5m
      source:
        repoURL: https://github.com/christianh814/ocp-sm-ar
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
